const listings = [
  {
    title: "Luxury Villa with Swimming Pool",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    location: "Luxury Villa with Swimming Pool, Goa",
    state: "Goa",
    country: "India",
  },
  {
    title: "Mountain View Cottage",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    location: "Mountain View Cottage, Manali",
    state: "Himachal Pradesh",
    country: "India",
  },
  {
    title: "Beach House",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    location: "Beach House, Pondicherry",
    state: "Puducherry",
    country: "India",
  },
  {
    title: "Modern Apartment",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    location: "Modern Apartment, Bangalore",
    state: "Karnataka",
    country: "India",
  },
  {
    title: "Lake Side Cabin",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    location: "Lake Side Cabin, Nainital",
    state: "Uttarakhand",
    country: "India",
  },
  {
    title: "Royal Heritage Palace",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    location: "Royal Heritage Palace, Jaipur",
    state: "Rajasthan",
    country: "India",
  },
  {
    title: "Snow View Chalet",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    location: "Snow View Chalet, Shimla",
    state: "Himachal Pradesh",
    country: "India",
  },
  {
    title: "Farm Stay",
    image: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c",
    location: "Farm Stay, Nashik",
    state: "Maharashtra",
    country: "India",
  },
  {
    title: "Desert Camp",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    location: "Desert Camp, Jaisalmer",
    state: "Rajasthan",
    country: "India",
  },
  {
    title: "City Studio Apartment",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    location: "City Studio Apartment, Mumbai",
    state: "Maharashtra",
    country: "India",
  },
  {
    title: "Forest Tree House",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
    location: "Forest Tree House, Wayanad",
    state: "Kerala",
    country: "India",
  },
  {
    title: "Backwater Villa",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    location: "Backwater Villa, Alleppey",
    state: "Kerala",
    country: "India",
  },
  {
    title: "Tea Garden Cottage",
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
    location: "Tea Garden Cottage, Munnar",
    state: "Kerala",
    country: "India",
  },
  {
    title: "Luxury Penthouse",
    image: "https://images.unsplash.com/photo-1460317442991-0ec209397118",
    location: "Luxury Penthouse, Delhi",
    state: "Delhi",
    country: "India",
  },
  {
    title: "Riverside Resort",
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607",
    location: "Riverside Resort, Rishikesh",
    state: "Uttarakhand",
    country: "India",
  },
  {
    title: "Hilltop Villa",
    image: "https://images.unsplash.com/photo-1516455207990-7a41ce80f7ee",
    location: "Hilltop Villa, Ooty",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    title: "Luxury Beach Resort",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    location: "Luxury Beach Resort, Kovalam",
    state: "Kerala",
    country: "India",
  },
  {
    title: "Eco Bamboo House",
    image: "https://images.unsplash.com/photo-1464890100898-a385f744067f",
    location: "Eco Bamboo House, Kaziranga",
    state: "Assam",
    country: "India",
  },
  {
    title: "Island Cottage",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    location: "Island Cottage, Andaman",
    state: "Andaman & Nicobar",
    country: "India",
  },
  {
    title: "Luxury Houseboat",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    location: "Luxury Houseboat, Srinagar",
    state: "Jammu & Kashmir",
    country: "India",
  }
];

module.exports = listings;